export enum StreetType {
  AL = "Alameda",
  AV = "Avenida",
  BC = "Beco",
  CAM = "Caminho",
  CH = "Chácara",
  EST = "Estrada",
  ETN = "Estância",
  FAZ = "Fazenda",
  PAR = "Paralela",
  R = "Rua",
  ROD = "Rodovia",
  SIT = "Sítio",
  TV = "Travessa",
}
